### ISSUE TITLE
paraview problem

### ISSUE THREAD

**Issue by x9m** [MinhNguyenIKM/dem_hyperelasticity#1]
Hi Minh,

I have a problem with Paraview. when I open your provided output vts files in Paraview. it doesn't show the deformed shapes.

is there anything i should do to correct this? much appreciated.

Regards,
Kun

**Comment by x9m** [comment]
yeah i find how to do it.

**Comment by MinhNguyenIKM** [comment]
Hi Kun,

Good to hear that you solved the problem.

Regards, Minh
